global_config:
  model_filename: "vocals_mel_band_roformer.ckpt"
  model_file_dir: "./models_cache"
  output_dir: "./stems"
  output_format: "wav"
  sample_rate: 48000
  use_autocast: true
stages:
 
  - name: "instrumental_primary"
    type: "separate"
    input_dir: "MIX"
    output_dir: "instrumental"
    models:
      - name: "UVR-Inst_HQ_5"
        model_file: "UVR-MDX-NET-Inst_HQ_5.onnx"
        output_single_stem: "Instrumental"
        mdx_params: {"hop_length": 1024, "segment_size": 512, "overlap": 0.75, "batch_size": 1, "enable_denoise": False}
        output_names: 
          Instrumental: "Instrumental"
      - name: "Kim-Inst"
        model_file: "Kim_Inst.onnx"
        output_single_stem: "instrumental"
        output_names: 
          instrumental: "Instrumental"
      - name: "MDX-NET-Inst-82"
        model_file: "UVR-MDX-NET_Inst_82_beta.onnx"
        output_single_stem: "Instrumental"
        mdx_params: {"hop_length": 1024, "segment_size": 512, "overlap": 0.75, "batch_size": 1, "enable_denoise": False}
        output_names: 
          Instrumental: "Instrumental"

  - name: "instrumental_mix_multistem"
    type: "separate"
    input_dir: "MIX"
    output_dir: "instrumental_multistem"
    models:
      - name: "BS-Roformer-SW"
        model_file: "BS-Roformer-SW.ckpt"
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"
          "guitar": "Guitar"
          "piano": "Piano"   
      - name: "htdemucs_6s"
        model_file: "htdemucs_6s.yaml"
        demucs_params: {"segment_size": 256, "shifts": 4, "overlap": 0.75, "segments_enabled": True}
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"
          "guitar": "Guitar"
          "piano": "Piano"
      - name: "htdemucs_ft"
        model_file: "htdemucs_ft.yaml"
        demucs_params: {"segment_size": 256, "shifts": 4, "overlap": 0.75, "segments_enabled": True}
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"        

  - name: "vocals_instrumental_multistem"
    type: "separate"
    input_dir: "vocals"
    filename_filter: "(Instrumental)"
    output_dir: "instrumental_multistem"
    models:
      - name: "BS-Roformer-SW"
        model_file: "BS-Roformer-SW.ckpt"
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"
          "guitar": "Guitar"
          "piano": "Piano"   
      - name: "htdemucs_6s"
        model_file: "htdemucs_6s.yaml"
        demucs_params: {"segment_size": 256, "shifts": 4, "overlap": 0.75, "segments_enabled": True}
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"
          "guitar": "Guitar"
          "piano": "Piano"
      - name: "htdemucs_ft"
        model_file: "htdemucs_ft.yaml"
        demucs_params: {"segment_size": 256, "shifts": 4, "overlap": 0.75, "segments_enabled": True}
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"        

  - name: "instrumental_multistem"
    type: "separate"
    input_dir: "instrumental"
    filename_filter: "(Instrumental)"
    output_dir: "instrumental_multistem"
    models:
      - name: "BS-Roformer-SW"
        model_file: "BS-Roformer-SW.ckpt"
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"
          "guitar": "Guitar"
          "piano": "Piano"   
      - name: "htdemucs_6s"
        model_file: "htdemucs_6s.yaml"
        demucs_params: {"segment_size": 256, "shifts": 4, "overlap": 0.75, "segments_enabled": True}
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"
          "guitar": "Guitar"
          "piano": "Piano"
      - name: "htdemucs_ft"
        model_file: "htdemucs_ft.yaml"
        demucs_params: {"segment_size": 256, "shifts": 4, "overlap": 0.75, "segments_enabled": True}
        output_names: 
          "vocals": "Vocals"
          "drums": "Drums"
          "bass": "Bass"
          "other": "Other"        

  - name: "drums_multistem"
    type: "separate"
    input_dir: "instrumental_multistem"
    output_dir: "instrumental_multistem_drums"
    filename_filter: "(Drums)"
    models:
      - name: "MDX23C-DrumSep-AJ"
        model_file: "MDX23C-DrumSep-aufr33-jarredou.ckpt"
        output_names: 
          "kick": "Kick"
          "snare": "Snare"
          "toms": "Toms"
          "hh": "Hihat"
          "ride": "Ride"
          "crash": "Crash"

  - name: "inst_debleed"
    type: "separate"
    input_dir: "instrumental_multistem"
    output_dir: "debleed"
    models:
      - name: "MBR-Denoise-Debleed-gabox"
        model_file: "mel_band_roformer_denoise_debleed_gabox.ckpt"
        output_single_stem: "Instrumental"
        output_names: 
          Instrumental: "Debleed"
      - name: "MBR-Bleed-Suppressor-v1"
        model_file: "mel_band_roformer_bleed_suppressor_v1.ckpt"
        output_single_stem: "Bleed"
        output_names: 
          Bleed: "Debleed"

  - name: "inst_ensemble_debleed"
    type: "ensemble"
    mode: "instrumental"
    combine: "avg"
    input_dir: "debleed"
    filename_filter: "(Instrumental)"
    output_dir: "ensemble"
    output_name: "Ensemble (Instrumental) (Debleed).wav"
    top_k: 5

  - name: "inst_ensemble"
    type: "ensemble"
    mode: "instrumental"
    combine: "avg"
    input_dir: "instrumental"
    filename_filter: "(Instrumental)"
    output_dir: "ensemble"
    output_name: "Ensemble (Instrumental).wav"

  - name: "bass_ensemble"
    type: "ensemble"
    mode: "instrumental"
    combine: "avg"
    input_dir: "debleed"
    filename_filter: "(Bass)"
    output_dir: "ensemble"
    output_name: "Ensemble (Bass).wav"    

  - name: "drums_ensemble"
    type: "ensemble"
    mode: "instrumental"
    combine: "avg"
    input_dir: "debleed"
    filename_filter: "(Drums)"
    output_dir: "ensemble"
    output_name: "Ensemble (Drums).wav"    

  - name: "drums_ensemble_kick"
    type: "ensemble"
    mode: "instrumental"
    combine: "avg"
    input_dir: "instrumental_multistem_drums"
    filename_filter: "(Kick)"
    output_dir: "ensemble"
    output_name: "Ensemble (Kick).wav"    

  - name: "drums_ensemble_snare"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem_drums"
    filename_filter: "(Snare)"
    output_dir: "ensemble"
    output_name: "Ensemble (Snare).wav"    

  - name: "drums_ensemble_toms"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem_drums"
    filename_filter: "(Toms)"
    output_dir: "ensemble"
    output_name: "Ensemble (Toms).wav"
    top_k: 5

  - name: "drums_ensemble_hihat"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem_drums"
    filename_filter: "(Hihat)"
    output_dir: "ensemble"
    output_name: "Ensemble (Hihat).wav"
    top_k: 5

  - name: "drums_ensemble_ride"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem_drums"
    filename_filter: "(Ride)"
    output_dir: "ensemble"
    output_name: "Ensemble (Ride).wav"
    top_k: 5

  - name: "drums_ensemble_crash"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem_drums"
    filename_filter: "(Crash)"
    output_dir: "ensemble"
    output_name: "Ensemble (Crash).wav"
    top_k: 5

  - name: "guitar_ensemble"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem"
    filename_filter: "(Guitar)"
    output_dir: "ensemble"
    output_name: "Ensemble (Guitar).wav"
    top_k: 5

  - name: "piano_ensemble"
    type: "ensemble"
    mode: "instrumental"
    input_dir: "instrumental_multistem"
    filename_filter: "(Piano)"
    output_dir: "ensemble"
    output_name: "Ensemble (Piano).wav"
    top_k: 5

  - name: "bass_midi"
    type: "midi"
    input_dir: "ensemble"
    output_dir: "ensemble_midi"
    filename_filter: "(Bass)"
    engines: ["basic_pitch"]

  - name: "guitar_midi"
    type: "midi"
    input_dir: "ensemble"
    output_dir: "ensemble_midi"
    filename_filter: "(Guitar)"
    engines: ["basic_pitch"]

  - name: "piano_midi"
    type: "midi"
    input_dir: "ensemble"
    output_dir: "ensemble_midi"
    filename_filter: "(Piano)"
    engines: ["basic_pitch"]    

  - name: "drums_midi"
    type: "midi"
    input_dir: "ensemble"
    output_dir: "ensemble_midi"
    filename_filter: "(Drums)"
    engines: ["omnizart"]